sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 0619
  alioss:
    bucket-name: web-gua-talis
    endpoint: https://oss-cn-beijing.aliyuncs.com
    region: cn-beijing
  redis:
    host: localhost
    port: 6379
    database: 10